-- INTEGRANTES:
-- Kenneth Ariel Chaves Herrera
-- Randall Sandoval Chavarría
-- William Arias Bermúdez
-- Brandon Rodríguez Rodríguez

ALTER SESSION SET "_Oracle_SCRIPT"=true;

CREATE USER SUPER IDENTIFIED BY superUsuario;

GRANT ALL PRIVILEGES TO SUPER;

CREATE TABLE SUPER.ROL
(
	PK_IDROL NUMBER(10),
	DESCRIPCION VARCHAR2(200),
	CONSTRAINT ROL_PK PRIMARY KEY (PK_IDROL)
);

CREATE TABLE SUPER.AREA
(
	PK_IDAREA NUMBER(10), 
	DESCRIPCION VARCHAR2(200),
	CONSTRAINT AREA_PK PRIMARY KEY (PK_IDAREA)
);

CREATE TABLE SUPER.USUARIO
(
	PK_IDUSUARIO NUMBER(10),
	FK_IDROL NUMBER(10),
	NOMBREUSUARIO VARCHAR2(50),
	CONTRASENA VARCHAR2(500),
	NOMBRE VARCHAR2(50),
	APELLIDO1 VARCHAR2(50),
	APELLIDO2 VARCHAR2(50),
	CONSTRAINT USUARIO_PK PRIMARY KEY (PK_IDUSUARIO),
	CONSTRAINT USUARIO_ROL_FK FOREIGN KEY (FK_IDROL) REFERENCES SUPER.ROL(PK_IDROL)
	
);

CREATE TABLE SUPER.GERENTEAREA
(
	PK_IDGERENTEAREA NUMBER(10),
	FK_IDUSUARIO NUMBER(10),
	FK_IDAREA NUMBER(10),
	CONSTRAINT GERENTEAREA_PK PRIMARY KEY (PK_IDGERENTEAREA),
	CONSTRAINT GERENTEAREA_USUARIO_FK FOREIGN KEY (FK_IDUSUARIO) REFERENCES SUPER.USUARIO(PK_IDUSUARIO),
	CONSTRAINT GERENTEAREA_AREA_FK FOREIGN KEY (FK_IDAREA) REFERENCES SUPER.AREA(PK_IDAREA)
);

CREATE TABLE SUPER.CAJERO
(
	PK_IDCAJERO NUMBER(10),
	FK_IDUSUARIO NUMBER(10),
	NUMEROCAJA NUMBER(2),
	CONSTRAINT CAJERO_PK PRIMARY KEY (PK_IDCAJERO),
	CONSTRAINT CAJERO_USUARIO_FK FOREIGN KEY (FK_IDUSUARIO) REFERENCES SUPER.USUARIO(PK_IDUSUARIO)
);

CREATE TABLE SUPER.PRODUCTO
(
	PK_IDPRODUCTO NUMBER(10),
	FK_IDAREA NUMBER(10),
	EAN NUMBER(13),
	DESCRIPCION VARCHAR2(200),
	PRECIO NUMBER(10, 2),
	CANTIDAD NUMBER(10),
	CONSTRAINT PRODUCTO_PK PRIMARY KEY (PK_IDPRODUCTO),
	CONSTRAINT PRODUCTO_AREA_FK FOREIGN KEY (FK_IDAREA) REFERENCES SUPER.AREA(PK_IDAREA)
);

CREATE TABLE SUPER.PRODUCTOFRESCO
(
	PK_IDFRESCO NUMBER(10),
	FK_IDPRODUCTO NUMBER(10),
	PLU NUMBER(5),
	PESO NUMBER(5, 2),
	CONSTRAINT PRODUCTOFRESCO_PK PRIMARY KEY (PK_IDFRESCO),
	CONSTRAINT PRODUCTOFRESCO_PRODUCTO_FK FOREIGN KEY (FK_IDPRODUCTO) REFERENCES SUPER.PRODUCTO(PK_IDPRODUCTO)
);

CREATE TABLE SUPER.FACTURA
(
	PK_IDFACTURA NUMBER(10),
	FK_IDCAJERO NUMBER(10),
	MONTO NUMBER(12, 2),
	FECHA DATE,
	CONSTRAINT FACTURA_PK PRIMARY KEY (PK_IDFACTURA),
	CONSTRAINT FACTURA_CAJERO_FK FOREIGN KEY (FK_IDCAJERO) REFERENCES SUPER.CAJERO(PK_IDCAJERO)
);

CREATE TABLE SUPER.FACTURAPRODUCTO
(
	PK_IDFACTURAPRODUCTO NUMBER(10),
	FK_IDFACTURA NUMBER(10),
	FK_IDPRODUCTO NUMBER(10),
	CANTIDAD NUMBER(10),
	SUBTOTAL NUMBER(10, 2),
	CONSTRAINT FACTURAPRODUCTO_PK PRIMARY KEY (PK_IDFACTURAPRODUCTO),
	CONSTRAINT FACTURAPRODUCTO_FACTURA_FK FOREIGN KEY (FK_IDFACTURA) REFERENCES SUPER.FACTURA(PK_IDFACTURA),
	CONSTRAINT FACTURAPRODUCTO_PRODUCTO_FK FOREIGN KEY (FK_IDPRODUCTO) REFERENCES SUPER.PRODUCTO(PK_IDPRODUCTO)
);

CREATE TABLE SUPER.BITACORAMOVIMIENTOS
(
	PK_IDBITACORAMOVIMIENTOS NUMBER(10),
	IDUSUARIO NUMBER(10),
	NOMBREUSUARIO VARCHAR2(50),
	TABLA VARCHAR2(50),
	TIPOTRANSACCION VARCHAR2(20),
	DESCRIPCION VARCHAR2(300),
	FECHA DATE,
	CONSTRAINT BITACORAMOVIMIENTOS_PK PRIMARY KEY (PK_IDBITACORAMOVIMIENTOS)
);

CREATE TABLE SUPER.BITACOCAJERO
(
	PK_IDBITACOCAJERO NUMBER(10),
	IDUSUARIO NUMBER(10),
	NOMBREUSUARIO VARCHAR2(50),
	NUMEROCAJA NUMBER(2),
	IDFACTURA NUMBER(10),
	FECHA DATE,
	CONSTRAINT BITACOCAJERO_PK PRIMARY KEY (PK_IDBITACOCAJERO)
);

CREATE TABLE SUPER.BITACORAFACTURA
(
	PK_IDBITACORAFACTURA NUMBER(10),
	IDFACTURA NUMBER(10),
	EAN NUMBER(13),
	CANTIDAD NUMBER(10),
	SUBTOTAL NUMBER(10, 2),
	TOTAL NUMBER(12, 2),
	IDUSUARIO NUMBER(10),
	NOMBREUSUARIO VARCHAR2(50),
	FECHA DATE,
	CONSTRAINT BITACORAFACTURA_PK PRIMARY KEY (PK_IDBITACORAFACTURA)
);
